### ISSUE TITLE
Too many arguements Error 

### ISSUE THREAD

**Issue by itsbalamurali** [shunsukeaihara/go-pocketsphinx#1]
Hi,

Thanks for the library first of all.
I am facing few issues i have setup both pocketsphinx, sphinx train and sphinxbase versions (5prealpha)

i am getting following errors during go program build process.

```
# github.com/shunsukeaihara/go-pocketsphinx
shunsukeaihara/go-pocketsphinx/pocketsphinx.go:132: too many arguments in call to _Cfunc_ps_nbest
shunsukeaihara/go-pocketsphinx/segment.go:39: too many arguments in call to _Cfunc_ps_seg_iter
shunsukeaihara/go-pocketsphinx/segment.go:45: too many arguments in call to _Cfunc_ps_nbest_seg
```

can you please help me?

Thanks in advance.

**Comment by yurijmikhalevich** [comment]
Hi @itsbalamurali,

I faced the same issue, fixed it and created pullrequest with a fix and few improvements: https://github.com/shunsukeaihara/go-pocketsphinx/pull/2.

Now you can use my fork: https://github.com/39dotyt/go-pocketsphinx

Simply install&import "github.com/39dotyt/go-pocketsphinx".

**Comment by itsbalamurali** [comment]
@39dotyt thankyou i fixed it myself too :smiley: :+1: 
May be in README you should mention the version of pocketsphinx to be used.
the latest changes work with prealpha5

**Comment by itsbalamurali** [comment]
Closing this issue.

Please use @39dotyt  fork  https://github.com/39dotyt/go-pocketsphinx

until the pull request is merged.
